app:
  name: my-golang-app
  env: development
  port: "3000"
  log-level: info
  origins:
    - origin: "*"
      allowMethods: "GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD"
      allowHeaders: "Origin, Content-Type, Accept, Authorization"

database:
  host: localhost
  port: "5432"
  user: postgres
  password: password
  name: golang
  ssl-mode: disable
  ddl-mode: create-drop
  reset: true
  GCInterval: 30s
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
